pipelines:
  - name: Test123
    steps:
      - name: test
        type: Bash
        configuration:
          integrations:
            - name: git
        execution:
          onExecute:
            - echo ${int_git_token} > /opt/test123
            - cat /opt/test123
