pipelines:
  - name: testSimple_custom_amith_1
    steps:
      - name: testSimple
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: f0001.jfrog-pipelines.com/docker-remote/jfrog/pipelines-u18node
                tag: "16"
                sourceRepository: docker-remote
                registry: registry
        execution:
          onExecute:
            - docker pull releases-docker.jfrog.io/jfrog/pipelines-u18node:16
            - echo "executing step 4..."
            - sleep 600
